name: Pipeline CI

on:
  push:
    - master
  pull_request:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurando Node
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    
    - name: Instalando dependencias
      run: npm install
    

    - name: Build
      run: npm run build

    - name: Test
      run: npm test